function [] = analysis_script(fpath)
% fpath = './results/14_gaussian_gamma_09'
load([fpath filesep 'results.mat']);
r_last = results.rewards(end);
n_state = 14;

results.b_before_observation = results.bT;
results.b_after_normalization = results.

%%
plot_difference( ...
    'Before observation', ...
    r_last, n_state, ...
    results.b_before_observation, ...
    zeros(size(results.b_before_observation)) ...
    );
ylim([0 1]);
saveas(gcf, [fpath filesep 'beleif_before_observation'], 'png');

plot_difference( ...
    'after normalization', ...
    r_last, n_state, ...
    results.b_after_normalization, ...
    zeros(size(results.b_before_observation)) ...
    );
ylim([0, 1]);
saveas(gcf, [fpath filesep 'belief_after_normalization'], 'png');

% weight
figure;
plot( ...
    results.w(r_last, 1:n_state) ...
    );
xlabel('State');
ylabel('Weight (a.u.)');
title('Weight')
saveas(gcf, [fpath filesep 'weight'], 'png');

%%
plot_difference( ...
    'Difference between before and observation', ...
    r_last, n_state, ...
    results.b_before_normalization, ...
    results.b_before_observation ...
    );
saveas(gcf, [fpath filesep 'difference_between_before_and_observation'], 'png');

%% 
plot_difference( ...
    'Difference between before observation and after normalization', ...
    r_last, n_state, ...
    results.b_after_normalization, ...
    results.b_before_observation ...
    );
saveas(gcf, [fpath filesep 'difference_between_before_observation_and_after_normalization'], 'png');

%%
figure('Name', 'Difference between values');
wins = (-(n_state-1):0)+r_last;

hold on
% plot( ...
%     results.value(wins), ...
%     'DisplayName', 'w * b0' ...
%     );
% plot( ...
%     results.pre_value(wins), ...
%     'DisplayName', 'w0 * b0' ...
%     );
% plot( ...
%     results.next_value(wins), ...
%     'DisplayName', 'w * b' ...
%     );
% plot( ...
%     results.next_value_before_learning(wins), ...
%     'DisplayName', 'w0 * b' ...
%     );
plot( ...
    results.next_value_before_learning(wins) - results.pre_value(wins), ...
    'DisplayName', 'w0 * (b - b0)' ...
    );
plot( ...
    results.value(wins) - results.pre_value(wins), ...
    'DisplayName', '(w - w0) *  b0' ...
    );
plot( ...
    results.next_value(wins) - results.value(wins), ...
    'DisplayName', 'w * (b - b0)' ...
    );
plot( ...
    results.next_value(wins) - results.pre_value(wins), ...
    'DisplayName', 'w * b - w0 * b0' ...
    );
hold off

title('Difference between values');
xlabel('Current state');
ylabel('Value (a.u.)');
xlim([1 n_state]);
legend('Location', 'bestoutside');
saveas(gcf, [fpath filesep 'difference_between_values'], 'png');

%%
figure('Name', 'RPE');
plot(results.rpe(wins));
title('RPE');
xlabel('Current state');
ylabel('RPE (a.u.)');
xlim([1 n_state]);
saveas(gcf, [fpath filesep 'rpe'], 'png');

%%
figure('Name', 'Resampled RPE');
load kernel_GCaMP6m_UnexpR.mat
resampled_rpe = resample(results.rpe(wins), 1000 * n_state, n_state);
plot( ...
    resampled_rpe, ...
    'DisplayName', 'Resampled RPE' ...
    );
hold on
plot ( ...
    conv(resampled_rpe, dn_y), ...
    'DisplayName', 'Convolution GCaMP' ...
    );
hold off
legend();
xlabel('Time (a.u.)');
title('Resampled RPE');
saveas(gcf, [fpath filesep 'resampled_rpe'], 'png');

%%
figure('Name', 'Value before/after observation');
hold on

value_mt0 = nan([1 n_state]);
value_mt1 = nan([1 n_state]);
for i = 1:n_state
    value_mt0(i) = ...
        results.w(wins(i), :) * results.b_before_observation(wins(i), :)';
    value_mt1(i) = ...
        results.w(wins(i), :) * results.b_after_normalization(wins(i), :)';
end
plot( ...
    value_mt0, ...
    'DisplayName', 'Before' ...
    );
plot( ...
    value_mt1, ...
    'DisplayName', 'After' ...
    );
hold off
legend();
xlabel('Internal state');
ylabel('Value (a.u.)');
title('Value before/after observation');
saveas(gcf, [fpath filesep 'value_before_after_observation'], 'png');

%%
figure('Name', 'Error between value before/after observation');
plot( ...
    value_mt1(1:end-1) - value_mt0(1:end-1) ...
    );
xlabel('Current state');
ylabel('Error (a.u.)');
title('Error before/after observation');
saveas(gcf, [fpath filesep 'error_before_after_observation'], 'png');
