function [idx, label] = make_windows(results)
    idx = (-14:1) + find(results.r == 1, 1, 'last');
    label = [ ...
        "CueOn", ...
        "Cue1", ...
        "Cue2", ...
        "Cue3", ...
        "Cue4", ...
        "Cue5", ...
        "Cue6", ...
        "Cue7", ...
        "Cue8", ...
        "Cue9", ...
        "Cue10", ...
        "Cue11", ...
        "Cue12", ...
        "Cue13", ...
        "Cue14", ...
        "ITI" ...
        ];
end
